---
development:
  host: localhost
  user: kuretsuki
  password: kure
  dbname: kuredb
  port: 5432
product:
  host: localhost
  user: kuretsuki
  password: kure
  dbname: productdb
  port: 5432
mode: development
